export const PLANEJAMENTO_VAZIO = {
  id: null,
  nome: '',
  tipo: 'semestre',
  periodo: { inicio: '', fim: '' },
  config: {
    nomeUsuario: 'Carla',
    horarioAula: '14:00',
    blocos: {
      manha: { inicio: '08:00', fim: '10:00', horas: 2 },
      tarde: { inicio: '14:00', fim: '16:00', horas: 2 },
      extra: { inicio: '19:00', fim: '21:00', horas: 2 },
    },
    estudoLivre: 'CC50 – Ciência da Computação de Harvard',
    moduloAtual: 'Módulo 1 – C',
    diasUteis: [1, 2, 3, 4, 5],
    fontSize: 16,
  },
  disciplinas: [],
  aulas: [],
  eventos: [],
  progresso: {
    aulasAssistidas: {},
    estudosConcluidos: {},
    edicoesManha: {},
  },
  stats: {
    totalDias: 0,
    diasEstudados: 0,
    prazosConcluidos: 0,
    prazosPendentes: 0,
    aulasAssistidas: 0,
    totalAulas: 0,
    porcentagemConcluido: 0,
  },
  arquivado: false,
  dataCriacao: null,
  dataArquivamento: null,
};